// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

module helloworld.helloworld;

import google.protobuf;
import google.rpc.status;

enum protocVersion = 3007000;

struct HelloRequest
{
    @Proto(1) string name = protoDefaultValue!string;
}

struct HelloReply
{
    @Proto(1) string message = protoDefaultValue!string;
}

interface Greeter
{
    @RPC("/helloworld.Greeter/SayHello")
    Status SayHello(HelloRequest, ref HelloReply);

}
